// Devin Security bridge — launches Devin code scans against the configured repos and
// reads back scan status / findings / remediation sessions via the Devin v3 API.
//
//   DEVIN_API_KEY      service-user or personal access token with UseCodeScans
//   DEVIN_ORG_ID       organization id (prefix org-)
//   CRUCIX_SCAN_REPOS  comma-separated owner/repo list the panel may scan
//   DEVIN_API_BASE     optional, defaults to https://api.devin.ai
//
// The token never leaves the server. When unconfigured every action throws
// DevinNotConfigured, which server.mjs maps to HTTP 503 with the env vars to set.

export const SCAN_STATUSES = ['waiting', 'pending', 'running', 'awaiting_user_input', 'completed', 'failed', 'cancelled'];
export const FINDING_STATUSES = ['open', 'dismissed', 'resolved'];
export const EFFORTS = ['normal', 'deep'];
export const REQUIRED_ENV = ['DEVIN_API_KEY', 'DEVIN_ORG_ID', 'CRUCIX_SCAN_REPOS'];

const REPO_RE = /^(?!\.+\/)[A-Za-z0-9_.-]+\/(?!\.+$)[A-Za-z0-9_.-]+$/;
const ID_RE = /^[A-Za-z0-9_-]{4,80}$/;

export class DevinNotConfigured extends Error {
  constructor(missing) {
    super(`Devin Security is not connected — set ${missing.join(', ')}`);
    this.name = 'DevinNotConfigured';
    this.missing = missing;
    this.status = 503;
  }
}

export class DevinApiError extends Error {
  constructor(status, detail) {
    super(`Devin API ${status}${detail ? `: ${detail}` : ''}`);
    this.name = 'DevinApiError';
    this.status = status;
    this.detail = detail;
  }
}

export function parseRepos(raw) {
  return [...new Set(String(raw || '').split(/[,\s]+/).map(s => s.trim()).filter(s => REPO_RE.test(s)))].slice(0, 50);
}

export function readConfig(env = process.env) {
  const repos = parseRepos(env.CRUCIX_SCAN_REPOS);
  const missing = [];
  if (!env.DEVIN_API_KEY) missing.push('DEVIN_API_KEY');
  if (!env.DEVIN_ORG_ID) missing.push('DEVIN_ORG_ID');
  if (!repos.length) missing.push('CRUCIX_SCAN_REPOS');
  return {
    configured: missing.length === 0,
    missing,
    repos,
    orgId: env.DEVIN_ORG_ID || null,
    base: (env.DEVIN_API_BASE || 'https://api.devin.ai').replace(/\/+$/, ''),
    token: env.DEVIN_API_KEY || null,
  };
}

// Public, token-free view for the dashboard.
export function publicStatus(env = process.env) {
  const c = readConfig(env);
  return {
    configured: c.configured,
    missing: c.missing,
    repos: c.repos,
    orgId: c.orgId ? `${c.orgId.slice(0, 8)}…` : null,
    hint: c.configured ? null : `Set ${c.missing.join(', ')} (fly secrets set … for production) and restart. No code change needed.`,
    docs: 'https://docs.devin.ai/api-reference/v3/code-scans/triggering-code-scans',
  };
}

// What this week's attack data says a scan should look for. Built from the live sweep so the
// panel is useful even before a key exists (the analyst can paste it into Devin by hand).
export function buildScanBrief(data = {}, { now = Date.now() } = {}) {
  const kev = data.cyberKev || {};
  const rw = data.ransomware || {};
  const products = (kev.byVendor || []).slice(0, 8).map(v => `${v.vendor} (${v.products.slice(0, 3).join(', ')})`);
  const dueSoon = (kev.dueSoon || []).slice(0, 5).map(v => `${v.cveID} ${v.vendor} ${v.product} due ${v.dueDate}`);
  const groups = (rw.groups || []).slice(0, 5).map(g => `${g.name} (${g.count} victims; ${g.sectors.slice(0, 2).join(', ')})`);
  const tools = [...new Set((rw.groups || []).flatMap(g => g.tools || []))].slice(0, 10);
  const lines = [
    'Security scan guidance generated by CRUCIX from live exploitation data.',
    `As of ${new Date(now).toISOString().slice(0, 16).replace('T', ' ')}Z.`,
    '',
    products.length ? `CISA KEV additions (last ${kev.deltaDays || 30} days) concentrate on: ${products.join('; ')}.` : 'CISA KEV data unavailable this sweep.',
    dueSoon.length ? `BOD 22-01 due soonest: ${dueSoon.join('; ')}.` : '',
    groups.length ? `Most active ransomware groups (leak-site claims, last ${rw.windowDays || 7} days): ${groups.join('; ')}.` : '',
    tools.length ? `Tooling seen with these groups: ${tools.join(', ')}.` : '',
    '',
    'Prioritize: dependencies and base images matching the vendors/products above; exposed admin/auth endpoints; file-upload and deserialization paths; secrets in config; outbound-call allowlists.',
    'Scope note: KEV entries for network appliances (NetScaler, FortiOS, Ivanti…) cannot be patched from a repository scan — report them as exposure to confirm, not as fixable findings.',
  ].filter(l => l !== '');
  return { text: lines.join('\n'), vendors: products, dueSoon, groups, tools };
}

export class DevinSecurity {
  constructor({ env = process.env, fetchImpl = globalThis.fetch, timeoutMs = 20000 } = {}) {
    this.env = env;
    this.fetch = fetchImpl;
    this.timeoutMs = timeoutMs;
  }

  get config() { return readConfig(this.env); }

  requireConfig() {
    const c = this.config;
    if (!c.configured) throw new DevinNotConfigured(c.missing);
    return c;
  }

  async call(method, path, { body, query } = {}) {
    const c = this.requireConfig();
    const qs = query ? '?' + new URLSearchParams(Object.entries(query).filter(([, v]) => v != null && v !== '')).toString() : '';
    const url = `${c.base}/v3/organizations/${encodeURIComponent(c.orgId)}${path}${qs}`;
    const ctrl = new AbortController();
    const timer = setTimeout(() => ctrl.abort(), this.timeoutMs);
    let res;
    try {
      res = await this.fetch(url, {
        method,
        headers: { authorization: `Bearer ${c.token}`, accept: 'application/json', ...(body ? { 'content-type': 'application/json' } : {}) },
        body: body ? JSON.stringify(body) : undefined,
        signal: ctrl.signal,
      });
    } catch (e) {
      throw new DevinApiError(502, e?.name === 'AbortError' ? 'timed out' : 'unreachable');
    } finally {
      clearTimeout(timer);
    }
    const text = await res.text().catch(() => '');
    let json = null;
    try { json = text ? JSON.parse(text) : null; } catch { json = null; }
    if (!res.ok) throw new DevinApiError(res.status, json?.detail || json?.title || json?.error || text.slice(0, 200));
    return json;
  }

  async startScan({ repo, effort = 'normal', interactive = false } = {}) {
    const c = this.requireConfig();
    if (!c.repos.includes(repo)) throw Object.assign(new Error(`repo not in CRUCIX_SCAN_REPOS: ${repo}`), { status: 400 });
    if (!EFFORTS.includes(effort)) throw Object.assign(new Error('effort must be normal or deep'), { status: 400 });
    const scan = await this.call('POST', '/code-scans', { body: { repo_name: repo, scan_type: 'security', effort, interactive: !!interactive } });
    return compactScan(scan);
  }

  async listScans({ repo, first = 20 } = {}) {
    const out = await this.call('GET', '/code-scans/scans', { query: { repo_name: repo, first } });
    return (out?.items || []).map(compactScan);
  }

  async listFindings({ scanId, status, first = 100 } = {}) {
    if (!ID_RE.test(String(scanId || ''))) throw Object.assign(new Error('scan_id required'), { status: 400 });
    const out = await this.call('GET', '/code-scans/findings', { query: { scan_id: scanId, status, first } });
    return (out?.items || []).map(compactFinding);
  }

  async remediate({ scanId, findingId } = {}) {
    if (!ID_RE.test(String(scanId || '')) || !ID_RE.test(String(findingId || ''))) throw Object.assign(new Error('scan_id and finding_id required'), { status: 400 });
    const out = await this.call('POST', `/code-scans/${encodeURIComponent(scanId)}/findings/${encodeURIComponent(findingId)}/remediate`, { body: {} });
    return { findingId: out?.finding_id || findingId, sessionId: out?.session_id || null, sessionUrl: out?.session_id ? `https://app.devin.ai/sessions/${String(out.session_id).replace(/^devin-/, '')}` : null };
  }
}

const s = (v, n = 200) => (v == null ? null : String(v).slice(0, n));

export function compactScan(x = {}) {
  return {
    scanId: s(x.scan_id, 80), repo: s(x.repo_name, 200), status: SCAN_STATUSES.includes(x.status) ? x.status : s(x.status, 40),
    scanType: s(x.scan_type, 40), effort: s(x.effort, 10), url: s(x.url, 300),
    createdAt: Number.isFinite(x.created_at) ? new Date(x.created_at * 1000).toISOString() : null,
    profile: x.profile?.name ? s(x.profile.name, 80) : null,
    findings: Number.isFinite(x.findings_count) ? x.findings_count : (Number.isFinite(x.num_findings) ? x.num_findings : null),
  };
}

export function compactFinding(x = {}) {
  return {
    findingId: s(x.finding_id, 80), scanId: s(x.scan_id, 80), repo: s(x.repo_name, 200),
    title: s(x.title, 160), severity: s(x.severity, 20), category: s(x.category || x.type, 60),
    status: FINDING_STATUSES.includes(x.status) ? x.status : s(x.status, 40),
    file: s(x.file_path || x.path || x.location?.file, 200),
    description: s(x.description || x.summary, 400),
    sessionId: s(x.session_id || x.remediation_session_id, 80),
    prUrl: s(x.pr_url || x.pull_request_url, 300),
    createdAt: Number.isFinite(x.created_at) ? new Date(x.created_at * 1000).toISOString() : null,
  };
}
